name: Frontier
version: '1.0'
main: net.azisaba.frontier.FrontierPlugin
description: Frontier Core
api-version: '1.21.11'
bootstrapper: net.azisaba.frontier.FrontierBootstrap
dependencies:
  server:
    TAB-BukkitBridge:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    WorldEdit:
      load: BEFORE
      required: false
    BlueMap:
      load: BEFORE
      required: false
permissions:
  frontier.user:
    default: true
  frontier.admin:
    default: op
